name: yangon_taxi_driver
description: "Yangon Taxi Driver App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # UI
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8

  # 状态管理 & 存储
  shared_preferences: ^2.3.2

  # 网络
  http: ^1.1.0

  # 多语言
  flutter_localizations:
    sdk: flutter
  intl: ">=0.19.0 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
